[payments]
rpcUrl = "https://api.devnet.solana.com"

[network]
bind_address = "0.0.0.0"
external_address = "0.0.0.0"
bind_port = 5555

[docker]
socket = "npipe:////./pipe/docker_engine"
address = "host.docker.internal"
responseTimeout = 30
connectionTimeout = 30
maxConnections = 1024

[registry]
indexers = {  }

[cache]
root_path = "C:\\Users\\seafr\\.coral"
indexer_cache_path = "C:\\Users\\seafr\\.coral\\registry"
agent_cache_path = "C:\\Users\\seafr\\.coral\\agent"

[security]
enableReferencedExporting = false