[agent]
name = "search"
version = "0.0.1"

[options]
OPENAI_API_KEY = { type = "string", description = "OpenAI API Key" }
GOOGLE_API_KEY = { type = "string", description = "Google API Key" }
SEARCH_ENGINE_ID = { type = "string", description = "Google Search Engine ID" }

[runtimes.executable]
command = ["bash", "examples/camel-search-maths/venv.sh", "examples/camel-search-maths/mcp_example_camel_math.py"]